version: '3.9'

services:
  goutomation-app:
    build: .
    container_name: goutomation
    ports:
      - "5000:5000"
    volumes:
      - .:/app                # Mount current directory into /app inside container
    working_dir: /app/backend   # Set working dir to backend folder (where main.py lives)
    environment:
      - FLASK_APP=main.py       # Because working dir is /app/backend
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
    command: flask run            # Run the flask server